# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B clean package  --file pom.xml
#     run: mvn -B package --file pom.xml

    - name: Archive WAR
      if: always()
      uses: actions/upload-artifact@v1
      with: 
        name: yaoqishan
        path: target/yaoqishan.war

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-1
    - name: Upload file to S3
      env: 
        S3_UPLOAD_BUCKET: skm-deploy-war
      run: |
        aws s3 cp authApiService.zip s3://$S3_UPLOAD_BUCKET/backend/ --quiet

